{% set version = "6.30" %}

package:
  name: pyfim
  version: {{ version }}

source:
  url: http://www.borgelt.net/src/pyfim.tar.gz
  sha256: ff24d48f2527fddc6c09dc649d302efc30bd5d877f71f5c09316ad1389279d52

build:
  number: 1
  script:
    - python setup.py build_ext --include-dirs=%PREFIX%\include --library-dirs=%PREFIX%\lib  # [win]
    - python setup.py build_ext --include-dirs=$PREFIX/include --library-dirs=$PREFIX/lib  # [not win]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fim

about:
  home: http://www.borgelt.net/pyfim.html
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/License'
  summary: 'Frequent item set mining'

  description: |
    PyFIM is an extension module that makes several frequent item set mining
    implementations available as functions in Python 2.7.x & 3.5.x. Currently
    apriori, eclat, fpgrowth, sam, relim, carpenter, ista, accretion and
    apriacc are available as functions, although the interfaces do not offer
    all of the options of the command line program. (Note that lcm is available
    as an algorithm mode of eclat.) There is also a "generic" function fim,
    which is essentially the same function as fpgrowth, only with a simplified
    interface (fewer options). Finally, there is a function arules for
    generating association rules (simplified interface compared to apriori,
    eclat and fpgrowth, which can also be used to generate association rules.
  doc_url: http://www.borgelt.net/pyfim.html
  dev_url: http://www.borgelt.net/pyfim.html

extra:
  recipe-maintainers:
    - CurtLH
