travis:
  secure:
    BINSTAR_TOKEN: tNCyrHrKR4Yqcv/ZdJIy2r+qFGaMp1UfkOAPuAPyrorZoMUXB2uJeo7CL3zTwVJH+nqRgmB25KlWFbrk6A7GmUZrUpN9/BsVKQEyU9Bs0yHi48JshYnLsbDwpKKJczv9n2vXthtRCq6Og8EHYGGafzn+PbIqkLiVwo/97BeNhmuSmLrNqLTiEacjwQj/265WWvzEITCBUf7KB01ylzUNtihd28RVIPyjlwnwcJOAHYiSgIp4xTPGavgJr/Hq99jhs9ef+V8HVEquVGG4XTlnJZY4Dt2GfXNf3X7OQOXMsI1JzLFJjUFhL+JGihowrbd9YxoPCAasaLoNZowBEjBEtjKhfWXgrnZA7atz3GkNWfzl4RF+PraXTdboSPwtViclogy4nwDSmyz2dtX0SdLzOkv/2F3xohTpD3/siHHOci4ztO8GgIiDO0lOk7xQ8E+pTxncDtApuS9grhw64YwmQmWmkjwOt1fKCoZB+6zjSVwLY3x4Q4/sHhbnxGHMtXi9KbqY0wLoEb7RX56/3q0b1bUUdze5uMQH1SoX7HX4p6lLvhVx8ky1fc5+fdQIPm31Efpp3chrXXt28/78mOfQec7MyLWHpjB6YbAVpaSWj5Y6xkdKWeWNrwuIA9TwXc9eRjA86YEpIg6Q09qSESwuZwCY8tOndJXOVmeDEbAQiEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
