travis:
  secure:
    BINSTAR_TOKEN: VIkxx0/OtPI8RQ8NYkvrVRXTlExvBKToPGaot/H1MNpP9euYTYCOgYnyFKOTThHFNtax3r2n4UfFo/Z+QlYFEKaZ+ES1PK0nWEZ1+UOgEleye4ZowEvhZhVQlrpuZci2hVWPmALPmvxgse8X0XWRpqDpxehW2MHcxZFP2Dj71KJ+Uf0amxIhkX/MZ9+hcPwKm225Ji8UJjexBHtn3dXW7e4O9RumY/J28MKPCUGi169yTFJm2eeExq4XDD9tDKpvNNp08BrXSAjHcbG/MMQIR1I9EzPgLdn3VNx6Kd0eu0bJMWcXiHnIGgLeWrbLEB7QC4ay5xy85MVjwoTDk2Hh6RUCFhT3t9HHQ5h5pa4r/hip9pjoOF2hRr+5wMeQ3ViNEVtdWgOcMgeq7uNbiIVdfr+Kt/yW1ZLumY2Pu4TpcFfrigg77F0oY3tvgEdpKy97bm+uQ47aPI+dz2zWUIoO7Qc7uvLV98qLY8CIAuUKHu7eWD4lrbMSSJ2/V2BnNb9i57+9daXulU4/v5ZXHvtGRj6/tpWt+zxOHvMebhJ11WGBduhVARzRAvZtyUah5q95EPJ4eScg5/f5ItfN8TEdkKI2Eu1i6oBYM8+/K5iucx3xc3IPp3CXpOWDgPTWzuo3sFbGXnr+rUt5p81fKXKHsqSK5sZ0SXTQAirER7+cdwA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
